### PR TITLE
updated README.md with instructions for Debian based systems. Add inf…

### PR DESCRIPTION
**Pull request by techantidote**
…ormation about python3-tk

### CODE REVIEW

**Comment by techantidote** [comment]
-The CLI app runs "os.system("color 0F")" which I believe was meant for MS based systems.
-If running the CLI app on *Nix systems, it will throw an error "sh: 1: color: not found"
-To fix this, Added check to see platform type. If Platform is Windows, then set color to 0f.

**Comment by techantidote** [comment]
-The CLI app runs "os.system("color 0F")" which I believe was meant for MS based systems.
-If running the CLI app on *Nix systems, it will throw an error "sh: 1: color: not found"
-To fix this, Added check to see platform type. If Platform is Windows, then set color to 0f. Removed print statement for os type.

**Comment by divagicha** [comment]
Thanks for contributing to this project. I will have a quick look to the changes as soon as possible and merge the request if found useful. Thanks again! :) Stay safe!!!

**Comment by techantidote** [comment]
@divagicha  Great!

**Pull request merged**
